
Tracker:AddLocations("locations/CityEscape.json")
Tracker:AddLocations("locations/WildCanyon.json")
Tracker:AddLocations("locations/PrisonLane.json")
Tracker:AddLocations("locations/MetalHarbor.json")
Tracker:AddLocations("locations/GreenForest.json")
Tracker:AddLocations("locations/PumpkinHill.json")
Tracker:AddLocations("locations/MissionStreet.json")
Tracker:AddLocations("locations/AquaticMine.json")
Tracker:AddLocations("locations/Route101.json")
Tracker:AddLocations("locations/HiddenBase.json")
Tracker:AddLocations("locations/PyramidCave.json")
Tracker:AddLocations("locations/DeathChamber.json")
Tracker:AddLocations("locations/EternalEngine.json")
Tracker:AddLocations("locations/MeteorHerd.json")
Tracker:AddLocations("locations/CrazyGadget.json")
Tracker:AddLocations("locations/FinalRush.json")

Tracker:AddLocations("locations/IronGate.json")
Tracker:AddLocations("locations/DryLagoon.json")
Tracker:AddLocations("locations/SandOcean.json")
Tracker:AddLocations("locations/RadicalHighway.json")
Tracker:AddLocations("locations/LostColony.json")
Tracker:AddLocations("locations/EggQuarters.json")
Tracker:AddLocations("locations/WeaponsBed.json")
Tracker:AddLocations("locations/SecurityHall.json")
Tracker:AddLocations("locations/WhiteJungle.json")
Tracker:AddLocations("locations/Route280.json")
Tracker:AddLocations("locations/SkyRail.json")
Tracker:AddLocations("locations/MadSpace.json")
Tracker:AddLocations("locations/CosmicWall.json")
Tracker:AddLocations("locations/FinalChase.json")

Tracker:AddLocations("locations/GreenHill.json")

Tracker:AddLocations("locations/GateBosses.json")
Tracker:AddLocations("locations/BossRushBosses.json")

Tracker:AddLocations("locations/KartRace.json")

Tracker:AddLocations("locations/Chao/ChaoGardenBeginner.json")
Tracker:AddLocations("locations/Chao/ChaoGardenIntermediate.json")
Tracker:AddLocations("locations/Chao/ChaoGardenExpert.json")
Tracker:AddLocations("locations/Chao/ChaoGardenKarate.json")

Tracker:AddLocations("locations/Chao/ChaoGardenStatSwim.json")
Tracker:AddLocations("locations/Chao/ChaoGardenStatFly.json")
Tracker:AddLocations("locations/Chao/ChaoGardenStatRun.json")
Tracker:AddLocations("locations/Chao/ChaoGardenStatPower.json")
Tracker:AddLocations("locations/Chao/ChaoGardenStatStamina.json")
Tracker:AddLocations("locations/Chao/ChaoGardenStatLuck.json")
Tracker:AddLocations("locations/Chao/ChaoGardenStatIntelligence.json")

Tracker:AddLocations("locations/Chao/animals/ChaoBat.json")
Tracker:AddLocations("locations/Chao/animals/ChaoBear.json")
Tracker:AddLocations("locations/Chao/animals/ChaoCheetah.json")
Tracker:AddLocations("locations/Chao/animals/ChaoCondor.json")
Tracker:AddLocations("locations/Chao/animals/ChaoDragon.json")
Tracker:AddLocations("locations/Chao/animals/ChaoGorilla.json")
Tracker:AddLocations("locations/Chao/animals/ChaoHalfFish.json")
Tracker:AddLocations("locations/Chao/animals/ChaoOtter.json")
Tracker:AddLocations("locations/Chao/animals/ChaoParrot.json")
Tracker:AddLocations("locations/Chao/animals/ChaoPeacock.json")
Tracker:AddLocations("locations/Chao/animals/ChaoPeguin.json")
Tracker:AddLocations("locations/Chao/animals/ChaoPhoenix.json")
Tracker:AddLocations("locations/Chao/animals/ChaoRabbit.json")
Tracker:AddLocations("locations/Chao/animals/ChaoRaccoon.json")
Tracker:AddLocations("locations/Chao/animals/ChaoSeal.json")
Tracker:AddLocations("locations/Chao/animals/ChaoSheep.json")
Tracker:AddLocations("locations/Chao/animals/ChaoSkeletonDog.json")
Tracker:AddLocations("locations/Chao/animals/ChaoSkunk.json")
Tracker:AddLocations("locations/Chao/animals/ChaoTiger.json")
Tracker:AddLocations("locations/Chao/animals/ChaoUnicorn.json")
Tracker:AddLocations("locations/Chao/animals/ChaoWarthog.json")

Tracker:AddLocations("locations/Chao/ChaoClassDrawing.json")
Tracker:AddLocations("locations/Chao/ChaoClassDance.json")
Tracker:AddLocations("locations/Chao/ChaoClassSong.json")
Tracker:AddLocations("locations/Chao/ChaoClassInstrument.json")

Tracker:AddLocations("locations/Chao/BlackMarket_1.json")
Tracker:AddLocations("locations/Chao/BlackMarket_2.json")
Tracker:AddLocations("locations/Chao/BlackMarket_3.json")
Tracker:AddLocations("locations/Chao/BlackMarket_4.json")
Tracker:AddLocations("locations/Chao/BlackMarket_5.json")
Tracker:AddLocations("locations/Chao/BlackMarket_6.json")
Tracker:AddLocations("locations/Chao/BlackMarket_7.json")
Tracker:AddLocations("locations/Chao/BlackMarket_8.json")

Tracker:AddLocations("locations/CannonsCore.json")